version: '3.8'
services:
  goetl:
    container_name: goetl
    build: .
    ports:
      - "8080:8080"
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - mongodb
  mongodb:
    image: mongo:7
    container_name: goetl-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    command: ["--auth"]

  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: goetl-swagger-ui
    ports:
      - "8081:8080"
    environment:
      SWAGGER_JSON: /docs/openapi.yaml
    volumes:
      - ./docs/openapi.yaml:/docs/openapi.yaml:ro

volumes:
  mongo_data:
